version: '3.1'

services:

  mysql:
    image: mysql:latest
    container_name: auth-base
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: auth-base
      MYSQL_USER: kassio
      MYSQL_PASSWORD: 'password'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql


volumes:
  mysql_data: